### ISSUE TITLE
Providing a sample

### ISSUE THREAD

**Issue by raandree** [ChrisLGardner/JeaDscDatum#1]
Hi Chris,

can you provide a sample how to use this? I would like to add the resource to https://github.com/AutomatedLab/CommonTasks then to make use of it in the https://github.com/AutomatedLab/DscWorkshop/.

**Comment by ChrisLGardner** [comment]
I'll try to dig out the samples I have for this, I think I have them still lying around somewhere.

**Comment by raandree** [comment]
Thanks in advance!

**Comment by ChrisLGardner** [comment]
Added in the Examples folder (https://github.com/ChrisLGardner/JeaDscDatum/tree/master/Examples). Hopefully that'll give you a good idea of what I've used while testing this. There's probably still a bit of work needed on this but I've been pretty busy so haven't had a chance to catch up on any other issues on JeaDsc or elsewhere.

**Comment by raandree** [comment]
Thanks! I will take a loot at it.
